
SELECT
  CAST(DELIVER_BY AS VARCHAR(7)) "MONTH",
  COUNT(*) "SHIPMENTS",
  CAST(SUM(WEIGHT) AS INTEGER) "TOTAL LBS",
  CAST(SUM(PALLETS) AS INTEGER) "TOTAL PLT",
  CAST(SUM(TOTAL_CHARGES) AS DECIMAL(10,2)) "TOTAL REVENUE",
  CAST(AVG(WEIGHT) AS INTEGER) "AVG LBS/SHIPMENT",
  CAST(AVG(PALLETS) AS INTEGER) "AVG PLT/SHIPMENT",
  CAST(AVG(TOTAL_CHARGES) AS DECIMAL(10,2)) "AVG REVENUE/SHIPMENT"
FROM TMWIN.TLORDER
WHERE CUSTOMER = ?
-- AND DATE(PICK_UP_BY) BETWEEN ? AND ?
AND CURRENT_STATUS NOT IN ('QUOTE','CANCL')
AND DOCUMENT_TYPE = 'INVOICE'
AND BILL_NUMBER NOT IN ('0','NA')
GROUP BY CAST(DELIVER_BY AS VARCHAR(7))

UNION ALL

SELECT
  'TOTAL' "MONTH",
  COUNT(*) "SHIPMENTS",
  CAST(SUM(WEIGHT) AS INTEGER) "TOTAL LBS",
  CAST(SUM(PALLETS) AS INTEGER) "TOTAL PLT",
  CAST(SUM(TOTAL_CHARGES) AS DECIMAL(10,2)) "TOTAL REVENUE",
  CAST(AVG(WEIGHT) AS INTEGER) "AVG LBS/SHIPMENT",
  CAST(AVG(PALLETS) AS INTEGER) "AVG PLT/SHIPMENT",
  CAST(AVG(TOTAL_CHARGES) AS DECIMAL(10,2)) "AVG REVENUE/SHIPMENT"
FROM TMWIN.TLORDER
WHERE CUSTOMER = ?
-- AND DATE(PICK_UP_BY) BETWEEN ? AND ?
AND CURRENT_STATUS NOT IN ('QUOTE','CANCL')
AND DOCUMENT_TYPE = 'INVOICE'
AND BILL_NUMBER NOT IN ('0','NA')

ORDER BY "MONTH"