SELECT
  T.BILL_NUMBER,
  T.DETAIL_LINE_ID,
  T.TRACE_NO,
  T.DESTNAME,
  T.DESTCITY,
  T.DESTPROV,
  T.DELIVERY_TERMINAL,
  DATE(T.PICK_UP_BY) "RECEIVED",
  DATE(CD2.DATE) "RPD",
  DATE(CD.DATE) "RAD",
  T.DELIVER_BY,
  T.DELIVER_BY_END,
  DATE(T.DELIVER_BY) - (DAYOFWEEK(DATE(T.DELIVER_BY))-1) DAYS "DELIVERY_WEEK",
  T.CREATED_TIME,
  TMWIN.KRC_GET_ARRCONS(T.DETAIL_LINE_ID) "ARRIVED"
FROM TMWIN.TLORDER T
LEFT JOIN TMWIN.CUSTOM_DATA CD
  ON CD.SRC_TABLE_KEY = T.DETAIL_LINE_ID
  AND CD.CUSTDEF_ID = 4
LEFT JOIN TMWIN.CUSTOM_DATA CD2
  ON CD2.SRC_TABLE_KEY = T.DETAIL_LINE_ID
  AND CD2.CUSTDEF_ID = 3
WHERE T.CURRENT_STATUS NOT IN ('CANCL','QUOTE')
AND T.DOCUMENT_TYPE = 'INVOICE'
AND TMWIN.KRC_IS_COMPLETE(T.DETAIL_LINE_ID) = 1
AND DATE(T.DELIVER_BY) BETWEEN '2016-06-26' AND CURRENT DATE
AND T.SITE_ID != 'SITEA'
