SELECT
  T.BILL_NUMBER,
  T.DETAIL_LINE_ID,
  T.TRACE_NO,
  T.DESTNAME,
  T.DESTCITY,
  T.DESTPROV,
  T.DELIVERY_TERMINAL,
  DATE(T.PICK_UP_BY) "RECEIVED",
  DATE(CD.DATE) "RAD",
  T.DELIVER_BY,
  T.DELIVER_BY_END
FROM TMWIN.TLORDER T
LEFT JOIN CUSTOM_DATA CD
  ON CD.SRC_TABLE_KEY = T.DETAIL_LINE_ID
  AND CD.CUSTDEF_ID = 4
WHERE T.CURRENT_STATUS NOT IN ('CANCL','QUOTE')
AND T.DOCUMENT_TYPE = 'INVOICE'
AND TMWIN.KRC_IS_COMPLETE(T.DETAIL_LINE_ID) = 1
AND T.SITE_ID != 'SITEA'
FETCH FIRST 200 ROWS ONLY