SELECT
  BILL_NUMBER,
  DETAIL_LINE_ID,
  TRACE_NO,
  DESTNAME,
  DESTCITY,
  DESTPROV,
  DELIVERY_TERMINAL,
  DATE(PICK_UP_BY) "RECEIVED",
  KRC_GET_RAD(DETAIL_LINE_ID) "RAD",
  DELIVER_BY,
  DELIVER_BY_END
FROM TLORDER
WHERE CURRENT_STATUS NOT IN ('CANCL','QUOTE')
AND DOCUMENT_TYPE = 'INVOICE'
AND KRC_IS_COMPLETE(DETAIL_LINE_ID) = 1
AND SITE_ID != 'SITEA'
FETCH FIRST 200 ROWS ONLY