SELECT
  CELL.RATING_ID "TARIFF",
  (
    SELECT LISTAGG(CRP.CLIENT_ID, ', ')
    FROM TMWIN.CLIENT_RATE_PROFILE CRP
    WHERE CRP.RATING_ID = CELL.RATING_ID
  ) "CUSTOMERS",
  HEAD.START_ZONE "ORIGIN",
  ZONE.ZONE_ID "ORIGIN_MS",
  ROW.TO_ZONE "DESTINATION",
  COL.BREAK_LABEL "BREAK",
  CELL.RATE_VALUE "RATE"
FROM TMWIN.RATE_CELL CELL
INNER JOIN TMWIN.RATE_HEADER HEAD
  ON HEAD.RATING_ID = CELL.RATING_ID
INNER JOIN TMWIN.RATE_ROW ROW
  ON CELL.RATE_ROW_ID = ROW.RATE_ROW_ID
  AND ROW.RATING_ID = CELL.RATING_ID
INNER JOIN TMWIN.RATE_COL COL
  ON CELL.RATE_COL_ID = COL.RATE_COL_ID
  AND COL.RATING_ID = CELL.RATING_ID
LEFT JOIN TMWIN.RATE_STARTZONES ZONE
  ON ZONE.RATING_ID = CELL.RATING_ID
WHERE ROW.TO_ZONE LIKE '432%'
AND HEAD.START_ZONE = 'STAL-TERM'