WITH ORDERS AS (
  SELECT
    BILL_NUMBER,
    DELIVER_BY,
    DATE(DELIVER_BY) - (DAYOFWEEK(DATE(DELIVER_BY))-1) DAYS "DELIVERY_WEEK",
    WEIGHT,
    CASE
      WHEN TMWIN.KRC_GET_COMPANY(DETAIL_LINE_ID) IS NOT NULL THEN
        TMWIN.KRC_GET_COMPANY(DETAIL_LINE_ID)
      WHEN TMWIN.KRC_GET_INTERLINER(DETAIL_LINE_ID) IS NOT NULL THEN
        13
    END "COMPANY"
  FROM TMWIN.TLORDER
  WHERE CURRENT_STATUS NOT IN ('CANCL','QUOTE')
  AND BILL_NUMBER NOT IN ('0','NA')
  AND END_ZONE NOT IN ('STAL-TERM','COMM-TERM','KELL-TERM')
  AND SITE_ID != 'SITEA'
  AND TMWIN.KRC_IS_COMPLETE(DETAIL_LINE_ID) = 1
  AND DELIVER_BY BETWEEN ((CURRENT DATE - (DAYOFWEEK(CURRENT DATE)-1) DAYS) - 1 YEAR)
    AND (CURRENT DATE - (DAYOFWEEK(CURRENT DATE)-1) DAYS)
)

SELECT

  -- TOTALS
  "DELIVERY_WEEK",
  COUNT(*) "NUM_ORDERS",
  CAST(SUM(WEIGHT) AS INTEGER) "WEIGHT",
  CAST(AVG(WEIGHT) AS INTEGER) "AVG_WEIGHT",


  -- KELLER
  (
    SELECT
    CASE
      WHEN COUNT(*) = 0 THEN
        NULL
      ELSE
        COUNT(*)
    END
    FROM ORDERS O2
    WHERE O2."DELIVERY_WEEK" = O."DELIVERY_WEEK"
    AND "COMPANY" = 10
  ) "NUM_ORDERS_10",
  (
    SELECT CAST(SUM(WEIGHT) AS INTEGER)
    FROM ORDERS O2
    WHERE O2."DELIVERY_WEEK" = O."DELIVERY_WEEK"
    AND "COMPANY" = 10
  ) "WEIGHT_10",
  (
    SELECT CAST(AVG(WEIGHT) AS INTEGER)
    FROM ORDERS O2
    WHERE O2."DELIVERY_WEEK" = O."DELIVERY_WEEK"
    AND "COMPANY" = 10
  ) "AVG_WEIGHT_10",


  -- COMMERCE LOCAL
  (
    SELECT
    CASE
      WHEN COUNT(*) = 0 THEN
        NULL
      ELSE
        COUNT(*)
    END
    FROM ORDERS O2
    WHERE O2."DELIVERY_WEEK" = O."DELIVERY_WEEK"
    AND "COMPANY" = 11
  ) "NUM_ORDERS_11",
  (
    SELECT CAST(SUM(WEIGHT) AS INTEGER)
    FROM ORDERS O2
    WHERE O2."DELIVERY_WEEK" = O."DELIVERY_WEEK"
    AND "COMPANY" = 11
  ) "WEIGHT_11",
  (
    SELECT CAST(AVG(WEIGHT) AS INTEGER)
    FROM ORDERS O2
    WHERE O2."DELIVERY_WEEK" = O."DELIVERY_WEEK"
    AND "COMPANY" = 11
  ) "AVG_WEIGHT_11",


  -- STALEY
  (
    SELECT
    CASE
      WHEN COUNT(*) = 0 THEN
        NULL
      ELSE
        COUNT(*)
    END
    FROM ORDERS O2
    WHERE O2."DELIVERY_WEEK" = O."DELIVERY_WEEK"
    AND "COMPANY" = 12
  ) "NUM_ORDERS_12",
  (
    SELECT CAST(SUM(WEIGHT) AS INTEGER)
    FROM ORDERS O2
    WHERE O2."DELIVERY_WEEK" = O."DELIVERY_WEEK"
    AND "COMPANY" = 12
  ) "WEIGHT_12",
  (
    SELECT CAST(AVG(WEIGHT) AS INTEGER)
    FROM ORDERS O2
    WHERE O2."DELIVERY_WEEK" = O."DELIVERY_WEEK"
    AND "COMPANY" = 12
  ) "AVG_WEIGHT_12",


  -- KRC LOGISTICS
  (
    SELECT
    CASE
      WHEN COUNT(*) = 0 THEN
        NULL
      ELSE
        COUNT(*)
    END
    FROM ORDERS O2
    WHERE O2."DELIVERY_WEEK" = O."DELIVERY_WEEK"
    AND "COMPANY" = 13
  ) "NUM_ORDERS_13",
  (
    SELECT CAST(SUM(WEIGHT) AS INTEGER)
    FROM ORDERS O2
    WHERE O2."DELIVERY_WEEK" = O."DELIVERY_WEEK"
    AND "COMPANY" = 13
  ) "WEIGHT_13",
  (
    SELECT CAST(AVG(WEIGHT) AS INTEGER)
    FROM ORDERS O2
    WHERE O2."DELIVERY_WEEK" = O."DELIVERY_WEEK"
    AND "COMPANY" = 13
  ) "AVG_WEIGHT_13",


  -- RTI
  (
    SELECT
    CASE
      WHEN COUNT(*) = 0 THEN
        NULL
      ELSE
        COUNT(*)
    END
    FROM ORDERS O2
    WHERE O2."DELIVERY_WEEK" = O."DELIVERY_WEEK"
    AND "COMPANY" = 14
  ) "NUM_ORDERS_14",
  (
    SELECT CAST(SUM(WEIGHT) AS INTEGER)
    FROM ORDERS O2
    WHERE O2."DELIVERY_WEEK" = O."DELIVERY_WEEK"
    AND "COMPANY" = 14
  ) "WEIGHT_14",
  (
    SELECT CAST(AVG(WEIGHT) AS INTEGER)
    FROM ORDERS O2
    WHERE O2."DELIVERY_WEEK" = O."DELIVERY_WEEK"
    AND "COMPANY" = 14
  ) "AVG_WEIGHT_14",


  -- COMMERCE REGIONAL
  (
    SELECT
    CASE
      WHEN COUNT(*) = 0 THEN
        NULL
      ELSE
        COUNT(*)
    END
    FROM ORDERS O2
    WHERE O2."DELIVERY_WEEK" = O."DELIVERY_WEEK"
    AND "COMPANY" = 15
  ) "NUM_ORDERS_15",
  (
    SELECT CAST(SUM(WEIGHT) AS INTEGER)
    FROM ORDERS O2
    WHERE O2."DELIVERY_WEEK" = O."DELIVERY_WEEK"
    AND "COMPANY" = 15
  ) "WEIGHT_15",
  (
    SELECT CAST(AVG(WEIGHT) AS INTEGER)
    FROM ORDERS O2
    WHERE O2."DELIVERY_WEEK" = O."DELIVERY_WEEK"
    AND "COMPANY" = 15
  ) "AVG_WEIGHT_15",


  -- UNDEFINED
  (
    SELECT
    CASE
      WHEN COUNT(*) = 0 THEN
        NULL
      ELSE
        COUNT(*)
    END
    FROM ORDERS O2
    WHERE O2."DELIVERY_WEEK" = O."DELIVERY_WEEK"
    AND "COMPANY" IS NULL
  ) "NUM_ORDERS_UNDEF",
  (
    SELECT CAST(SUM(WEIGHT) AS INTEGER)
    FROM ORDERS O2
    WHERE O2."DELIVERY_WEEK" = O."DELIVERY_WEEK"
    AND "COMPANY" IS NULL
  ) "WEIGHT_UNDEF",
  (
    SELECT CAST(AVG(WEIGHT) AS INTEGER)
    FROM ORDERS O2
    WHERE O2."DELIVERY_WEEK" = O."DELIVERY_WEEK"
    AND "COMPANY" IS NULL
  ) "AVG_WEIGHT_UNDEF"


FROM ORDERS O
GROUP BY "DELIVERY_WEEK"
ORDER BY "DELIVERY_WEEK" DESC
